// Array of answers objects with sample data for tests
module.exports = [
  {
    name: "FFF",
    textColor: "000000",
    fontFamily: "Tahoma",
    fontSize: "55",
    shape: "square",
    shapeColorType: "solid",
    shapeColor: "blue",
    strokeWidth: "0",
  },
  {
    name: "DLS",
    textColor: "lightgrey",
    fontFamily: "Georgia",
    fontSize: "72",
    shape: "circle",
    shapeColorType: "gradient",
    shapeColor: "darkgrey",
    shapeColor2: "purple",
    gradientDirection: "top-to-bottom",
    strokeWidth: "4",
    strokeColor: "purple",
  },
  {
    name: "SVG",
    textColor: "white",
    fontFamily: "Tahoma",
    fontSize: "72",
    shape: "circle",
    shapeColorType: "gradient",
    shapeColor: "yellow",
    shapeColor2: "red",
    gradientDirection: "left-to-right",
    strokeWidth: "0",
  },
  {
    name: "STO",
    textColor: "lightgrey",
    fontFamily: "Arial",
    fontSize: "66",
    shape: "polygon",
    points: "8",
    shapeColorType: "solid",
    shapeColor: "red",
    strokeWidth: "10",
    strokeColor: "lightgrey",
  },
  {
    name: "YYZ",
    textColor: "lavender",
    fontFamily: "Verdana",
    fontSize: "66",
    shape: "polygon",
    points: "6",
    shapeColorType: "gradient",
    shapeColor: "DarkGoldenRod",
    shapeColor2: "PapayaWhip",
    gradientDirection: "top-to-bottom",
    strokeWidth: "0",
  },
  {
    name: "KCH",
    textColor: "white",
    fontFamily: "Trebuchet MS",
    fontSize: "55",
    shape: "triangle",
    shapeColorType: "gradient",
    shapeColor: "purple",
    shapeColor2: "green",
    gradientDirection: "diagonally",
    strokeWidth: "7",
    strokeColor: "black",
  },
  {
    name: "G",
    textColor: "red",
    fontFamily: "Courier New",
    fontSize: "88",
    shape: "polygon",
    points: "9",
    shapeColorType: "gradient",
    shapeColor: "pink",
    shapeColor2: "lavender",
    gradientDirection: "left-to-right",
    strokeWidth: "1",
    strokeColor: "black",
  },
  {
    name: 'BB',
    textColor: 'darkblue',
    fontFamily: 'Verdana',
    fontSize: '72',
    shape: 'polygon',
    points: '5',
    shapeColorType: 'gradient',
    shapeColor: 'lightgrey',
    shapeColor2: 'lightblue',
    gradientDirection: 'diagonally',
    strokeWidth: '6',
    strokeColor: 'darkblue'
  },
];
